### PR TITLE
Load configuration from the environment

### PR DESCRIPTION
**Pull request by christiannelson**
Differences between prod and acceptance should be configurable via the environment. This is the "12-factor" way and also what Heroku recommends. In fact, Heroku now raises a warning when you deploy an app in any RAILS_ENV other than production.

This eliminates the hooks for configuring acceptance via acceptance.rb.

**Question** Is there anything in any of your current apps that necessitates the existence of acceptance.rb and the configuration therein?

### CODE REVIEW

**Comment by eskfung** [comment]
One practical differentiation between acceptance and production for us was in securing Heroku Redis. We've set up stunnel to secure the redis instance responsible for Sidekiq jobs. In acceptance, Heroku Redis is on the hobby tier, and trying to secure it results in the app completely timing out.

> SSL for Heroku Redis is only available on production tier plans. The hobby-tier plans are meant for testing and staging environments, not production. https://devcenter.heroku.com/articles/securing-heroku-redis

That said, I'm sure we could update our production config to accommodate. Just a scenario to point out.

**Comment by mattbrictson** [comment]
I'm on board with this. Like @eskfung said, we could accommodate rare cases where there are differences between acceptance and production by adding conditions to the production config. E.g. `if ENV["ENABLE_STUNNEL"] ...`

I'll rebase and merge this if there are no objections?

**Comment by christiannelson** [comment]
@mattbrictson Do you mind rebasing and sitting it for a little while. I had another real-world challenge with it that I can't recall at the moment. Want to see if I can dig it up.

**Comment by mattbrictson** [comment]
Rebased. Will hold off merging for now

**Comment by mattbrictson** [comment]
@christiannelson @eskfung in light of today's Slack discussion is this OK to merge?

**Comment by mattbrictson** [comment]
It works! https://test-acceptance.herokuapp.com

**Pull request merged**
