### PR TITLE
Auto run "yarn install" in bin/setup, bin/update

### PR DESCRIPTION
**Pull request by mattbrictson**
Problem
=======

Before, for a project with JavaScript dependencies a developer would have to remember to uncomment the `yarn install` line in `bin/setup`.

Solution
========

Now, `bin/setup` automatically runs `yarn install` based on the presence of a `yarn.lock` file. I made this change to `bin/update` as well.

Change summary:
---------------

```ruby
system!("bin/yarn") if File.exist?("yarn.lock")
```

### CODE REVIEW

**Comment by mattbrictson** [comment]
Hmm good catch. It seems weird that raygun-rails comes with a `yarn.lock` but lacks a `package.json`. Perhaps the `yarn.lock` should be removed?

**Comment by mattbrictson** [comment]
It seems that `yarn install` exits gracefully even if no `package.json` exists, so perhaps it is OK as-is.

**Comment by mattbrictson** [comment]
I'll follow up with Christian since the `yarn.lock` was introduced in his commit 82745c5d8698a69b91402e4f4dcc00874bcf5901

**Comment by eskfung** [comment]
I wonder why `yarn` is getting run in the first place... out of curiosity, does it regenerate if you precompile assets locally?

**Comment by mattbrictson** [comment]
Talked with Christian and we agreed that the empty `yarn.lock` was weird and unnecessary. For comparison, `rails new` does not create a empty `yarn.lock`. So I removed it.

**Comment by mattbrictson** [comment]
@eskfung still good to merge?

**Comment by eskfung** [comment]
Yep, go for it. :shipit:

**Pull request merged**
