### PR TITLE
Move .env out of git; explain local config steps

### PR DESCRIPTION
**Pull request by mattbrictson**
In a real-world project, `.env` will contain credentials and other secrets that should not be checked into git. Therefore we should remove it from source control and use a template to create a local copy for each developer that is then ignored by git.

### CODE REVIEW

**Comment by andrewhao** [comment]
Other projects I've been on have used a `.env.development` file to load a development-specific set of environment variables. I don't think this comes for free though; it comes with the `dotenv` gem which I don't believe we use in Raygun.

**Comment by christiannelson** [comment]
A little background on why I checked a .env in, despite it seeming a little controversial...

I strive to make it very easy for a new developer to be able to get up and running. Having to create a `.env` or copy a `.env.development` seemed like an extra step, *assuming* nothing for production (or staging) is checked in to `.env`... which shouldn't be the case (esp with a just zapped new app).

Now that rails (and raygun) has a setup script, I can imagine adding a `.env.development` (or whatever) file and copying it to `.env` if it doesn't already exist as part of the setup script.

Or we can leave it to an exercise for the reader, so the speak. I don't have a strong feeling about it, as long as whatever we come up with is very simple and works in a majority of the cases.

**Comment by christiannelson** [comment]
Related: I generally don't like setups scripts too, because they make it easy to do unconventional --
 and complicating -- things. I'd rather try to keep an app so simple to set up that no script is necessary. That ship has sailed with Rails' addition of the setup and update scripts. But in spirit, I still think it's important to embrace KISS and avoid anomalies.

**Comment by andrewhao** [comment]
Oh wait, sorry. I re-read the code (was reading the PR from the train). We still check in the file as a .env.sample, but it gets copied over and excluded from git. That seems perfectly reasonable to me, as long as the developer is aware of it (it's in the README).

**Comment by mattbrictson** [comment]
Sorry, I realize I didn't explain the PR very well.

Basically, this PR brings raygun-rails into alignment with the standard for most Rails apps I've encountered, which is:

1. The git repo has a sample .env file (in this PR I name it `.env.sample`)
2. Running `bin/setup` copies this sample file to `.env`, if it does not already exist
3. `/.env` is listed in `.gitignore` so that the credentials and other sensitive data that is typically stored in `.env` are not accidentally committed to the repo

To @christiannelson's point, this is slightly less convenient and out-of-the-box than just doing `git clone` and your `.env` is all ready to go: you have to explicitly run `bin/setup` (or create the `.env` file by hand). But I think it is a win overall from a security perspective, since most apps will eventually rely on sensitive data in environment variables.

**Comment by christiannelson** [comment]
I think this looks good... now that I looked at the changes, not just the conversation. :)

Only thought, and it could be another PR (or nothing at all), is that there's some duplication between the env vars section of the README and `.env.sample`. We _could_ move it all to `.env.sample` an annotate each entry. Just a thought.

**Comment by mattbrictson** [comment]
I think ultimately the README is the best place to document the env vars. For a production deploy you wouldn't actually use `.env` (you'd use Heroku config instead), and so the `.env.sample` doesn't feel like an appropriate place to document those. Also many vars are applicable to production only (e.g. `HOSTNAME`, `FORCE_SSL`, `RAILS_SERVE_STATIC_FILES`); I don't think those belong in `.env.sample`.

I think `.env.sample` should contain the bare minimum keys that you need to provide to boot the app locally (in practice, this may actually be zero). And then the README would be more comprehensive. That might mean some duplication is unavoidable.

Perhaps a separate PR could clean that up a bit?

**Comment by christiannelson** [comment]
@mattbrictson Mind rebasing this on top of the latest from master (rails 5.2)? I approve of it's merge if you want to merge it too.

**Comment by mattbrictson** [comment]
I'll rebase and merge 👍

**Pull request merged**
