### PR TITLE
Move Yarn and other required dependencies into a Brewfile for easier

### PR DESCRIPTION
**Pull request by rpak**
Problem
=======

Yarn is missing as an external dependency.

Solution
========
* Add Yarn dependency and installation step using `brew`

Change summary:
---------------
Moved Yarn and existing required dependencies into a Brewfile.

Steps to Verify:
----------------
1. Uninstall `yarn`
1. Verify failure running `./bin/setup`
1. `brew bundle --no-lock`
1. Verify `./bin/setup` succeeds

### CODE REVIEW

**Review by eskfung — APPROVED** [review]
✨

**Review by mattbrictson — COMMENTED** [review]
Hmm, I am not sure I want to advocate that yarn be installed via `brew`. If you do that you are indirectly installing node as well. Homebrew will always give you the latest node version which may not be what you want. Typically projects pin their node based on what they are running in CI and production, which is usually whatever the LTS version is. E.g. right now the LTS of node is node 12, but Homebrew will give you node 14.

Maybe this point is moot because currently raygun-rails does not prescribe a specific version of node. The `package.json` simply says it has to be >= 10.

The alternative would be either:

1. Update the README to say you have to have node + yarn installed, and it is up to the developer to figure out how (just like we say Ruby 2.7 is required but leave that as an exercise to the reader).
2. Advocate for a specific node version manager like nvm or nodenv.

Thoughts? /cc @eskfung @bunnymatic

**Comment by eskfung** [comment]
> it is up to the developer to figure out how (just like we say Ruby 2.7 is required but leave that as an exercise to the reader)

Right, totally fair 👍

**Comment by rpak** [comment]
I would like to advocate for explicitly adding a Node.js dependency and adding node version manager support. `.node-version` and a symlinked `.nvmrc` should support all the major version managers. I'm also okay with just adding documentation about having to figure out how to install node.js and yarn.

https://github.com/carbonfive/raygun-rails/pull/421/commits/fb95a689926c9419bae145165457493d77706244

**Comment by eskfung** [comment]
> .node-version and a symlinked .nvmrc should support all the major version managers

Seems fair to me. I personally use asdf and can confirm this. https://github.com/asdf-vm/asdf-nodejs#nvmrc-and-node-version-files

**Review by mattbrictson — APPROVED** [review]
Looks good! I was worried that `yarn` installed via homebrew would use the homebrew version node regardless of `.node-version`, but I verified that this is not the case. 👍

**Comment by bunnymatic** [comment]
A little late to the game but - I agree with @mattbrictson .  Letting `brew` install `yarn` *if* you always get the latest seems bad.  And because there are still differences with how folks manage `node` (`nvm`, `asdf`, `docker` images)... we should make sure this is pretty flexible. 

What are the repercussions for those who don't use `brew`?  I know it sounds ridiculous but there are developers on `Linux` and `windows` machines.  Does this just become a no-op?

**Comment by mattbrictson** [comment]
Seems like we are in agreement on the need to make the Node version explicit and call out the yarn requirement. But maybe not going so far as introducing a `Brewfile`. I will put together a slimmer PR.

**Comment by mattbrictson** [comment]
Closed for now in favor of #437

**Pull request closed without merging**
